data<-read.csv2(file="household_power_consumption.txt",sep=";",skip=66637,nrows=2880,col.names=c("date","time","globactpow","globreacctpow","volt","globint","sub1","sub2","sub3"))
datetime <- strptime(paste(data$date,data$time,sep =' '), format= '%d/%m/%Y %H:%M:%S')
png(filename = "plot4.png")
par(mfrow=c(2,2))
plot(datetime,as.numeric(data$globactpow),type="l",xlab="",ylab="Global Active Power")
plot(datetime,as.numeric(data$volt),type="l",ylab="Voltage")
plot(datetime,as.numeric(data$sub1),type="l",ylab="Energy sub metering",xlab="")
lines(datetime,as.numeric(data$sub2),col="red")
lines(datetime,as.numeric(data$sub3),col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(datetime,as.numeric(data$globreacctpow),type="l",ylab="Global_reactive_power")
dev.off()
